#!/usr/bin/env python3
"""make_review_pdf.py — one-page summary of the Supp Fig 3c class II addition, for review.

Builds `classII_summary_for_review.pdf`: the class II triads with release dates,
both metrics, provenance, and the figure itself — for John and Brandon to verify before
this goes into the reviewer response.

**Every number is read from the tracked CSVs, never typed in.** The table, the three
correlations and the post-cutoff check are all computed here, so the PDF cannot drift from
`merged_tv_rmsd_pae.csv` the way a hand-written summary would. It also refuses to build if
any triad fails the cutoff check, rather than print a claim that is no longer true.

    python make_review_pdf.py          # -> classII_summary_for_review.pdf

Needs tectonic (`brew install tectonic`), per this repo's LaTeX convention.
"""
import os
import shutil
import subprocess
import sys

import pandas as pd
from scipy.stats import pearsonr, spearmanr

HERE = os.path.dirname(os.path.abspath(__file__))
MERGED = os.path.join(HERE, "merged_tv_rmsd_pae.csv")
SUMMARY = os.path.join(HERE, "classII_summary_for_review.csv")
FIGURE = os.path.join(HERE, "plot_rmsd_vs_pae_classI_II.png")
TEX = os.path.join(HERE, "classII_summary_for_review.tex")
CUTOFF = pd.Timestamp("2023-01-12")


def esc(s):
    s = "" if s is None else str(s)
    for a, b in [("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"), ("_", r"\_"),
                 ("#", r"\#"), ("$", r"\$"), ("{", r"\{"), ("}", r"\}")]:
        s = s.replace(a, b)
    return s


def stats(g):
    rp, pp = pearsonr(g["x"], g["cdr_rmsd"])
    rs, ps = spearmanr(g["x"], g["cdr_rmsd"])
    return len(g), rp, pp, rs, ps


def main():
    for f in (MERGED, SUMMARY, FIGURE):
        if not os.path.exists(f):
            sys.exit(f"missing input: {f}")

    m = pd.read_csv(MERGED)
    m["x"] = 31 - m["pti_pae"]
    rows = [("MHC class I", stats(m[m.mhc_class == "I"])),
            ("MHC class II", stats(m[m.mhc_class == "II"])),
            ("combined", stats(m))]

    d = pd.read_csv(SUMMARY)
    d["rel"] = pd.to_datetime(d["release_date"])
    d = d.sort_values("cdr_rmsd")
    if not (d["rel"] > CUTOFF).all():
        sys.exit("a triad is not post-cutoff — refusing to build a PDF claiming otherwise")
    margin = (d["rel"].min() - CUTOFF).days
    earliest = d.loc[d["rel"].idxmin(), "pdb"]

    body = []
    for _, r in d.iterrows():
        b0, b1 = (r"\textbf{", "}") if r.cdr_rmsd > 10 else ("", "")
        body.append(
            f"{b0}\\texttt{{{esc(r.pdb)}}}{b1} & {r.rel.date()} & {b0}{r.cdr_rmsd:.2f}{b1} & "
            f"{r.pti_pae:.2f} & \\texttt{{\\scriptsize {esc(r.peptide)}}} & "
            f"{esc(r.mhc_1_name)} & {esc(r.on_johns_tsv)} & "
            f"{'published run' if 'published' in str(r.source) else 'newly folded'} \\\\")

    stat_rows = "\n".join(
        f"{esc(lab)} & {n} & ${rp:+.2f}$ & {pp:.3f} & ${rs:+.2f}$ & {ps:.3f} \\\\"
        for lab, (n, rp, pp, rs, ps) in rows)

    tex = r"""\documentclass[10pt]{article}
\usepackage[margin=0.65in,top=0.55in,bottom=0.5in]{geometry}
\usepackage{booktabs,graphicx,xcolor,array}
\usepackage{helvet}\renewcommand{\familydefault}{\sfdefault}
\setlength{\parindent}{0pt}\setlength{\parskip}{5pt}
\definecolor{hl}{HTML}{A32D2D}
\pagestyle{empty}

\begin{document}

{\LARGE\bfseries Supp.\ Fig.\ 3c --- MHC class II extension}\\[3pt]
{\large Reviewer round 2, minor point 1 --- \textit{``repeat this analysis using a larger
benchmark set''}}\\[3pt]
{\color{gray}\small For verification before the response goes out. Generated by
\texttt{make\_review\_pdf.py}; every number read from the tracked CSVs.}

\vspace{2pt}\hrule\vspace{6pt}

\textbf{What changed.} The published panel was \textbf{16 class I} post-training-cutoff
triads. It now carries \textbf{10 class II} as well. The class I points are
\emph{untouched} --- same CSV, same transform, same colour, same statistics, enforced by a
regression check (\texttt{plot\_supp3c.py -{}-check}) that fails rather than publish a
moved result.

\textbf{Five of the ten needed no new inference.} They were already folded in the
published \texttt{pdb.nf} run for Figure~1; Supp.\ Fig.\ 3c had simply been drawing from a
validation table that is class~I only. Their CDR RMSD was already computed
(\texttt{cdr\_rmsd\_af3\_0}, seed 0, exactly as the class~I points were), so only PTI-PAE
needed extracting --- which reads existing predictions and needs no GPU. That extraction
was verified by running \texttt{8enh} and \texttt{8es9} through it alongside: both
reproduce their published values to the last digit.

\textbf{Two were excluded on chemistry.} \texttt{8trl} and \texttt{8trr} are
\textbf{citrullinated} epitopes ($\alpha$-enolase and vimentin on HLA-DR4). Citrulline has
no standard one-letter code, so RCSB canonicalises it to arginine and AF3 folds a
different chemistry from the deposit --- and for these epitopes the modification is the
point, since DR4's shared-epitope pocket repels arginine and it is citrullination that
creates the neo-epitope. Both were post-cutoff, already folded, and predicted well (3.34
and 1.22\,\AA), so they are omitted on chemistry rather than on quality, consistent with
the rule applied elsewhere in the project. Removing them \emph{strengthened} every
statistic: class~II Spearman went from $-0.61$ to $-0.73$ and the combined Spearman from
$p=0.008$ to $p=0.001$.

\textbf{Five were newly folded} through the pipeline's own
\texttt{COMPOSE\_INFERENCE\_JSON} and \texttt{INFERENCE} (MSAs on, 5 seeds, 1 diffusion
sample), then measured with the same four processes \texttt{pdb.nf} uses for its own RMSDs.

\vspace{1pt}
\begin{center}\small
\begin{tabular}{@{}llrrlllc@{}}
\toprule
\textbf{PDB} & \textbf{released} & \textbf{CDR RMSD} & \textbf{PTI-PAE} &
\textbf{peptide} & \textbf{MHC} & \textbf{on TSV} & \textbf{prediction} \\
 & & (\AA) & & & & & \\
\midrule
""" + "\n".join(body) + r"""
\bottomrule
\end{tabular}
\end{center}

\textbf{All """ + str(len(d)) + r""" are post-training-cutoff.} AF3's cutoff is
\textbf{""" + CUTOFF.strftime("%Y-%m-%d") + r"""}, taken from \texttt{clean\_pdb.py}, which
cites the AF3 paper's data-availability statement. The earliest release here is
\texttt{""" + esc(earliest) + r"""} at """ + str(d["rel"].min().date()) + r""" ---
\textbf{""" + f"{margin}" + r""" days} past it. This is distinct from
\texttt{max\_template\_date}, which defaults to 2021-09-30 and caps what templates AF3 may
retrieve, so no structure here could have been handed its own answer.

\vspace{1pt}
\begin{center}\small
\begin{tabular}{@{}lrrrrr@{}}
\toprule
 & \textbf{n} & \textbf{Pearson r} & \textbf{p} & \textbf{Spearman} $\rho$ & \textbf{p} \\
\midrule
""" + stat_rows + r"""
\bottomrule
\end{tabular}
\end{center}

Class II is significant on its own and \emph{stronger} than class~I, on an independent set.

\vspace{2pt}\hrule\vspace{4pt}

{\large\bfseries Three things to check}

\textbf{1. \texttt{27eb} is not on the TSV} --- we derived it from RCSB rather than taking
it from a published listing. See below.

\textbf{2. \textcolor{hl}{\texttt{27eb} is the outlier, and the most informative point.}}
It is the least confident (PTI-PAE 17.5) \emph{and} least accurate (22.2\,\AA) triad in the
class~II set --- AF3 docks it badly and PTI-PAE flagged it in advance. It sits with
\texttt{8gom}/\texttt{8gon}, the class~I reverse-dock failures, which is the reviewer's
question answered in a single point. It was flagged as suspicious on confidence
\emph{before} its RMSD was computed. All five of its chains matched deposited entities
exactly and its crystal copy was chosen on measured contact geometry, so the input is
sound --- but it is the one triad without a published-listing provenance, and so the point
a reviewer is most likely to question.

\textbf{3. Two copies per asymmetric unit} in \texttt{9yaf}, \texttt{9yag} and
\texttt{27eb}. Chains were not taken by index order --- the published table has
\texttt{8trl} pairing MHC \texttt{A}/\texttt{B} with TCR \texttt{I}/\texttt{J}, so index
order is not reliably copy order. Each candidate was checked against deposited coordinates,
and every selected chain sits 4--7\,\AA{} from the MHC $\alpha$ chain.

\newpage
\vspace*{\fill}
{\large\bfseries Supp.\ Fig.\ 3c, extended}\\[2pt]
{\color{gray}\small CDR RMSD vs AF3 PTI-PAE on post-training-cutoff cognate triads. Blue is
the published 16 class~I points, unchanged; red is the 12 class~II points added here.
Dashed lines are per-class fits --- pooling them would assert a relationship the combined
statistics support only weakly, since the two classes sit at different absolute PTI-PAE.
Regenerated by \texttt{plot\_supp3c.py -{}-check}.}

\vspace{6pt}
\begin{center}
\includegraphics[width=\textwidth]{""" + os.path.basename(FIGURE) + r"""}
\end{center}
\vspace*{\fill}

\end{document}
"""
    with open(TEX, "w") as f:
        f.write(tex)

    if not shutil.which("tectonic"):
        sys.exit("tectonic not found — brew install tectonic")
    r = subprocess.run(["tectonic", os.path.basename(TEX)], cwd=HERE,
                       capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit((r.stdout[-2500:] or "") + "\n" + (r.stderr[-2500:] or ""))
    print("wrote", TEX.replace(".tex", ".pdf"))


if __name__ == "__main__":
    main()
